Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -3,6 +3,9 @@
 
 name: Go
 
+env:
+  GIN_MODE: release
+
 on:
   push:
     branches: [ "main" ]
@@ -13,6 +16,8 @@ jobs:
 
   build:
     runs-on: ubuntu-latest
+    permissions:
+      checks: write
     steps:
     - uses: actions/checkout@v4
 
@@ -21,8 +26,20 @@ jobs:
       with:
         go-version: '1.20'
 
-    - name: Build
-      run: go build -v ./...
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
+
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1.3.0
 
     - name: Test
-      run: go test -v ./...
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
