Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,46 +1,52 @@
 # This workflow will build a golang project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
 
-name: Go
+    name: Go
 
-env:
-  GIN_MODE: release
+    env:
+      GIN_MODE: release
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    on:
+      push:
+        branches: [ "main" ]
+      pull_request:
+        branches: [ "main" ]
 
-jobs:
+    jobs:
+      build:
+        runs-on: ubuntu-latest
 
-  build:
-    runs-on: ubuntu-latest
-    permissions:
-      checks: write
-    steps:
-    - uses: actions/checkout@v4
+        permissions:
+          checks: write
 
-    - name: Set up Go
-      uses: actions/setup-go@v4
-      with:
-        go-version-file: 'go.mod'
-        cache: true
+        steps:
+        - uses: actions/checkout@v3
 
-    - name: Revive Action
-      uses: morphy2k/revive-action@v2.4.1
+        - name: Set up Go
+          uses: actions/setup-go@v3
+          with:
+            go-version-file: 'go.mod'
+            cache: true
 
-    - name: Staticcheck
-      uses: dominikh/staticcheck-action@v1.3.0
+        - name: Revive Action
+          uses: morphy2k/revive-action@v2.4.1
 
-    - name: Test
-      run: |
-        gotestsum --format=standard-verbose --junitfile=junit.xml
+        - name: Staticcheck
+          uses: dominikh/staticcheck-action@v1.3.0
 
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/junit.xml'
-        detailed_summary: true
-        include_passed: true
+        - name: Build
+          run: |
+            go mod download
+            go install gotest.tools/gotestsum@latest
+
+        - name: Test
+          run: |
+            gotestsum --format=standard-verbose --junitfile=junit.xml
+
+        - name: Publish Test Report
+          uses: mikepenz/action-junit-report@v3
+          if: success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: '**/junit.xml'
+            detailed_summary: true
+            include_passed: true
